package org.ntk.mutibo.android.model;

public enum TaskType {
	LOGIN, RETRIEVE_DEMO, START_GAME, FINISH_GAME, NEXT_ITEMSET, ANSWER_ITEMSET, 
	START_DEMO_GAME, LIKE_ITEMSET, DISLIKE_ITEMSET, LOAD_USERS, REGISTER_USER, REQUEST_GAME;
}
